/* This file was auto-generated by MC-GENERATOR, DO NOT modify it manually */
/* eslint-disable import/exports-last, @typescript-eslint/naming-convention */
import { InputType, ObjectType, Field, Resolver, registerEnumType } from "type-graphql";
import { GraphQLScalarType } from "graphql";
import { mockEnum } from "mockPackage";

@InputType()
export class MockLayerInput {
    @Field((type) => [String], { nullable: true })
    public idStringArray?: string[];
    @Field((type) => String, { nullable: true })
    public idString?: string;
    @Field((type) => [LinkInput], { nullable: true })
    public idInputArray?: LinkInput[];
    @Field((type) => LinkInput, { nullable: true })
    public idInput?: LinkInput;
    @Field({ nullable: true })
    public lifecycleEnvolvedFalse?: string;
    @Field({ nullable: true })
    public autoGeneratedFalse?: string;
    @Field({ nullable: true })
    public source?: string;
    @Field({ nullable: true })
    public id?: string;
    @Field((type) => mockEnum, { nullable: true })
    public mockEnum?: mockEnum;
    @Field((type) => [mockEnum], { nullable: true })
    public mockEnumArray?: mockEnum[];
    @Field((type) => mockScalarObject, { nullable: true })
    public mockScalar?: Record<string, unknown>;
    @Field((type) => [String], { nullable: true })
    public stringArray?: String[];
}

export const mockScalarObject = new GraphQLScalarType({ name: "mockScalarObject"});

@ObjectType()
export class MockLayer {
    @Field((type) => [String], { nullable: true })
    public idStringArray?: string[];
    @Field((type) => String, { nullable: true })
    public idString?: string;
    @Field((type) => [LinkInput], { nullable: true })
    public idInputArray?: LinkInput[];
    @Field({ nullable: true })
    public lifecycleEnvolvedTrue?: string;
    @Field({ nullable: true })
    public lifecycleEnvolvedFalse?: string;
    @Field({ nullable: true })
    public autoGeneratedTrue?: string;
    @Field({ nullable: true })
    public autoGeneratedFalse?: string;
    @Field({ nullable: true })
    public source?: string;
    @Field({ nullable: true })
    public id?: string;
    @Field((type) => mockEnum, { nullable: true })
    public mockEnum?: mockEnum;
    @Field((type) => [mockEnum], { nullable: true })
    public mockEnumArray?: mockEnum[];
    @Field((type) => mockScalarObject, { nullable: true })
    public mockScalar?: Record<string, unknown>;
    @Field((type) => [String], { nullable: true })
    public stringArray?: String[];
}

@Resolver(MockLayer)
export class MockLayerResolver {
}

const mockEnumRegister = registerEnumType(mockEnum, {name: "mockEnum"});
