/* This file was auto-generated by MC-GENERATOR, DO NOT modify it manually */
import { ObjectType, Field, Resolver, registerEnumType } from "type-graphql";
import { GraphQLScalarType } from "graphql";
import { mockEnum } from "mockPackage";

@ObjectType()
export class MockLayer {
    @Field({ nullable: true })
    source?: string;
    @Field({ nullable: true })
    id?: string;
    @Field((type) => mockEnum, { nullable: true })
    mockEnum?: mockEnum;
    @Field((type) => mockScalarObject, { nullable: true })
    mockScalar?: string;
    @Field((type) => [String], { nullable: true })
    stringArray?: String[];
}

export const mockScalarObject = new GraphQLScalarType({ name: "mockScalarObject"});

@Resolver(MockLayer)
export class MockLayerResolver {
}

const mockEnumRegister = registerEnumType(mockEnum, {name: "mockEnum"});
