import { SourceFile } from 'ts-morph';

const AUTO_GENERATED_COMMENT = '/* This file was auto-generated by MC-GENERATOR, DO NOT modify it manually */';
const TSLINT_DISABLE_COMMENT = '/* eslint-disable */';

export const generateTopComments = (targetFile: SourceFile): void => {
  targetFile.insertStatements(0, AUTO_GENERATED_COMMENT + '\n' + TSLINT_DISABLE_COMMENT);
};
